# Generated by Django 6.0.2 on 2026-03-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MySQLConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='连接名称')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(default=3306, verbose_name='端口')),
                ('database', models.CharField(max_length=100, verbose_name='数据库名称')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MySQL 连接',
                'verbose_name_plural': 'MySQL 连接',
            },
        ),
    ]
