# Generated by Django 6.0.2 on 2026-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlconnection',
            name='status',
            field=models.CharField(choices=[('active', '已连接'), ('inactive', '未连接')], default='inactive', max_length=10, verbose_name='连接状态'),
        ),
    ]
