# Generated by Django 6.0.2 on 2026-03-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_mysqlconnection_status'),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlconnection',
            name='environments',
            field=models.ManyToManyField(blank=True, to='environments.environment', verbose_name='所属环境'),
        ),
    ]
