# Generated by Django 6.0.2 on 2026-03-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_mysqlconnection_environments'),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlconnection',
            name='environments',
        ),
        migrations.AddField(
            model_name='mysqlconnection',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.environment', verbose_name='所属环境'),
        ),
    ]
