# Generated by Django 6.0.2 on 2026-03-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_remove_mysqlconnection_environments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlconnection',
            name='database',
        ),
    ]
