# Generated by Django 6.0.2 on 2026-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='标签颜色'),
        ),
    ]
