# Generated by Django 6.0.2 on 2026-03-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='environments',
            field=models.ManyToManyField(blank=True, to='environments.environment', verbose_name='可访问环境'),
        ),
    ]
