# Generated by Django 6.0.2 on 2026-03-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('query', '查询'), ('login', '登录'), ('logout', '登出'), ('create_connection', '创建连接'), ('update_connection', '更新连接'), ('delete_connection', '删除连接'), ('create_masking', '创建脱敏规则'), ('update_masking', '更新脱敏规则'), ('delete_masking', '删除脱敏规则')], max_length=20)),
                ('sql', models.TextField(blank=True, null=True, verbose_name='SQL 语句')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(ms)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='connections.mysqlconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
