# Generated by Django 6.0.2 on 2026-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='execution_time',
            field=models.FloatField(blank=True, null=True, verbose_name='执行时间(ms)'),
        ),
    ]
