# Generated by Django 6.0.2 on 2026-03-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_mysqlconnection_status'),
        ('queries', '0003_systemconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='查询名称')),
                ('sql', models.TextField(verbose_name='SQL 语句')),
                ('database', models.CharField(blank=True, max_length=200, verbose_name='数据库名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_queries', to='connections.mysqlconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '保存的查询',
                'verbose_name_plural': '保存的查询',
                'ordering': ['-updated_at'],
            },
        ),
    ]
