# Generated by Django 6.0.2 on 2026-03-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('queries', '0004_savedquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.environment', verbose_name='环境'),
        ),
    ]
