# Generated by Django 6.0.2 on 2026-03-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, verbose_name='表名')),
                ('column_name', models.CharField(max_length=100, verbose_name='列名')),
                ('masking_type', models.CharField(choices=[('full', '完全脱敏'), ('partial', '部分脱敏'), ('regex', '正则匹配')], max_length=20, verbose_name='脱敏类型')),
                ('masking_params', models.JSONField(blank=True, null=True, verbose_name='脱敏参数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masking_rules', to='connections.mysqlconnection')),
            ],
            options={
                'verbose_name': '脱敏规则',
                'verbose_name_plural': '脱敏规则',
                'unique_together': {('connection', 'table_name', 'column_name')},
            },
        ),
    ]
