# Generated by Django 6.0.2 on 2026-03-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desensitization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maskingrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='maskingrule',
            name='column_names',
            field=models.JSONField(default=list, verbose_name='列名列表'),
        ),
        migrations.AddField(
            model_name='maskingrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masking_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='maskingrule',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='maskingrule',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='maskingrule',
            name='table_name',
        ),
    ]
