# Generated by Django 6.0.2 on 2026-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desensitization', '0002_alter_maskingrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskingrule',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='规则名称'),
        ),
    ]
