# Generated by Django 6.0.2 on 2026-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desensitization', '0003_maskingrule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskingrule',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
